# Generated by Django 4.2.6 on 2023-10-13 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_remove_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10, verbose_name='Total price'),
        ),
    ]
